language: php

php:
  - 7.3

env:
  - dependencies=lowest
  - dependencies=highest

before_script:
  - composer self-update
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi;

install:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.sample.xml
  - vendor/bin/phpstan analyze -l 7 source
